version: "3"

services:
    flask_app:
        build: .
        restart: always
        ports:
            - "80:5000"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
        links:
            - postgres
        depends_on:
            - postgres
        container_name: flask_app

    postgres:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
        volumes:
            - .postgres-data:/var/lib/postgresql/data
        container_name: flask_postgres
